# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ddb9132a0e07336649921716d440f0ef17ab7b77b3f3020744277187a066f07acc74c65d7ab85b2992d52f586512cf851a50d3efa383c8d5f53042268a5617a

test:
  secret_key_base: 4ba244399a4af26becb975ec48d48f4dea61d08e70a62be45d290dd7682ac1103bdac04af266514947677f73850fed25d0961a5192e20b44cb0433ef3f97c6f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
